## 1. Problem Definition:
* Goal: predict the sales price for each house

## 2. Feature Selection:
* Choose features to train ML Model
* Need to uese 'Feature Engineering' to indentify Features needed

## 3. Spliting the datasets

3.1. dataset -> X,y
* 'data': dataset
* 'x': data[features]
* 'y': target variable SalePrice
3.2. X,y -> X_train, y_train, X_valid, y_valid

## 4. Trainning Machine Learning Model

In [35]:
#Import Libraries
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
data = pd.read_csv("train.csv")

In [3]:
data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [4]:
data = pd.read_csv("train.csv", index_col = "Id")

In [5]:
data.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

In [6]:
data.columns

# Explain in link below:
# https://www.kaggle.com/c/home-data-for-ml-course/data

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'Wo

## 2. Feature Selecttions

In [7]:
features = ["LotArea", "YearBuilt", "1stFlrSF", "2ndFlrSF", "FullBath", "BedroomAbvGr", "TotRmsAbvGrd"]

## 3. Splitting dataset into X and y

In [8]:
X = data[features]
y = data["SalePrice"]

In [9]:
data.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

In [10]:
X.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                   
1      8450       2003       856       854         2             3   
2      9600       1976      1262         0         2             3   
3     11250       2001       920       866         2             3   
4      9550       1915       961       756         1             3   
5     14260       2000      1145      1053         2             4   

    TotRmsAbvGrd  
Id                
1              8  
2              6  
3              6  
4              7  
5              9

In [11]:
y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

## X,y -> X_train, y_train, X_valid, y_valid

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X,y, train_size=0.8, test_size = 0.2, random_state=0)

In [13]:
X_train.shape

(1168, 7)

In [14]:
X.shape

(1460, 7)

In [15]:
data.shape

(1460, 80)

In [16]:
X_valid.shape

(292, 7)

## 4. Trainning Machine Learning Model

In [17]:
from sklearn.tree import DecisionTreeRegressor

dt_model = DecisionTreeRegressor(random_state=1)

In [18]:
## Fit trainning data into model
dt_model.fit(X_train, y_train)

DecisionTreeRegressor(random_state=1)

In [19]:
y_preds = dt_model.predict(X_valid)

In [20]:
y_preds

array([335000., 140200., 119000., 207500., 112000.,  58500., 232600.,
       119500., 755000., 156932., 213500., 100000., 244000., 130000.,
       144900., 123000., 236000., 126000., 154500., 128000., 141500.,
       149000.,  62383., 186500., 139000., 135000., 195000.,  92000.,
       271000., 105500., 141000., 178000., 110000., 258000., 253293.,
       177000., 190000., 130000., 210000., 315750., 237500., 174000.,
       176000., 326000., 290000., 142600., 105500., 142500., 146500.,
       135000., 315750., 124000., 218000., 126000., 184000., 130000.,
       119500., 226700., 160000.,  87000., 142000.,  55993., 140000.,
       155000., 290000., 174000.,  97000., 205950., 147000., 207500.,
       176000., 109000., 139000., 194500., 115000., 230000., 132500.,
       109500., 325300.,  90000., 135960., 134900., 127000., 147000.,
       197000., 194700.,  86000., 202500., 198900.,  60000., 188000.,
       177000., 174000., 238000., 206000.,  80000., 190000., 223500.,
        88000., 1350

In [21]:
pd.DataFrame({'y': y_valid, 'y_preds' : y_preds})

y   y_preds
Id                    
530   200624  335000.0
492   133000  140200.0
460   110000  119000.0
280   192000  207500.0
656    88000  112000.0
...      ...       ...
327   324000  260400.0
441   555000  451950.0
1388  136000  107500.0
1324   82500   72500.0
62    101000   37900.0

[292 rows x 2 columns]

In [22]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
rf_model = RandomForestRegressor(random_state=1)
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=1)

In [23]:
rf_val_preds = rf_model.predict(X_valid)

In [24]:
rf_val_preds[:5]

array([271690., 155039., 122024., 188915.,  91147.])

In [25]:
X_valid.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                    
530    32668       1957      2515         0         3             4   
492     9490       1941       958       620         1             3   
460     7015       1950       979       224         1             3   
280    10005       1977      1156       866         2             4   
656     1680       1971       525       567         1             3   

     TotRmsAbvGrd  
Id                 
530             9  
492             5  
460             5  
280             8  
656             6

In [26]:
# Predict with a new input
# Create a DataFrame for the new input with the same column names
new_input = pd.DataFrame([[6969, 2021, 1000, 800, 4, 5, 8]], columns=features)

# Predict using the model
prediction_data = rf_model.predict(new_input)


In [27]:
prediction_data

array([206158.4])

## 5. Evaluate Model

In [32]:
predicted_data = pd.DataFrame({
    'LotArea': X_valid['LotArea'],
    'YearBuilt': X_valid['YearBuilt'],
    '1stFlrSF': X_valid['1stFlrSF'],
    '2ndFlrSF': X_valid['2ndFlrSF'],
    'FullBath': X_valid['FullBath'],
    'BedroomAbvGr': X_valid['BedroomAbvGr'],
    'TotRmsAbvGrd': X_valid['TotRmsAbvGrd']
})

In [31]:
rf_model = RandomForestRegressor(random_state=1)
rf_model.fit(data[features], data['SalePrice'])  # 'SalePrice' là giá nhà thực tế (giả định)


RandomForestRegressor(random_state=1)

In [33]:
predicted_prices = rf_model.predict(predicted_data)

In [36]:
# Đánh giá mô hình

mae = mean_absolute_error(y_valid, predicted_prices)
mse = mean_squared_error(y_valid, predicted_prices)
rmse = np.sqrt(mse)
r2 = r2_score(y_valid, predicted_prices)


In [37]:
print(f"Mean Absolute Error: {mae:.2f}")
print(f"Mean Squared Error: {mse:.2f}")
print(f"Root Mean Squared Error: {rmse:.2f}")
print(f"R-squared: {r2:.2f}")

Mean Absolute Error: 8410.01
Mean Squared Error: 173705725.51
Root Mean Squared Error: 13179.75
R-squared: 0.97
